26-03-2017 16:42:36.9 [INFO] App initiated
26-03-2017 16:43:16.0 [INFO] App initiated
26-03-2017 16:46:49.1 [INFO] App initiated
26-03-2017 17:20:47.1 [INFO] App initiated
26-03-2017 18:01:47.2 [INFO] App initiated
26-03-2017 18:03:07.3 [INFO] App initiated
26-03-2017 18:07:07.3 [INFO] App initiated
26-03-2017 18:12:45.4 [INFO] App initiated
26-03-2017 18:14:59.2 [INFO] App initiated
26-03-2017 18:16:25.3 [INFO] App initiated
26-03-2017 18:17:49.3 [INFO] App initiated
26-03-2017 18:18:51.6 [INFO] App initiated
26-03-2017 18:21:26.5 [INFO] App initiated
26-03-2017 18:23:30.2 [INFO] App initiated
26-03-2017 18:31:59.1 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 18:31:59.1 [ERROR] {"code":"E_UNEXPECTED","err_trace":"TypeError: A value function wrappedPointCut() {\n        var Promise = PromiseProvider.get();\n\n        var _this = this;\n        var args = [].slice.call(arguments);\n        var lastArg = args.pop();\n        var fn;\n        var originalError = new Error();\n        var $results;\n        if (lastArg && typeof lastArg !== 'function') {\n          args.push(lastArg);\n        } else {\n          fn = lastArg;\n        }\n\n        var promise = new Promise.ES6(function(resolve, reject) {\n          args.push(function(error) {\n            if (error) {\n              // gh-2633: since VersionError is very generic, take the\n              // stack trace of the original save() function call rather\n              // than the async trace\n              if (error instanceof VersionError) {\n                error.stack = originalError.stack;\n              }\n              _this.$__handleReject(error);\n              reject(error);\n              return;\n            }\n\n            // There may be multiple results and promise libs other than\n            // mpromise don't support passing multiple values to `resolve()`\n            $results = Array.prototype.slice.call(arguments, 1);\n            resolve.apply(promise, $results);\n          });\n\n          _this[_newName].apply(_this, args);\n        });\n        if (fn) {\n          if (this.constructor.$wrapCallback) {\n            fn = this.constructor.$wrapCallback(fn);\n          }\n          return promise.then(\n            function() {\n              process.nextTick(function() {\n                fn.apply(null, [null].concat($results));\n              });\n            },\n            function(error) {\n              process.nextTick(function() {\n                fn(error);\n              });\n            });\n        }\n        return promise;\n      } was yielded that could not be treated as a promise\n\n    See http://goo.gl/MqrFmX\n\nFrom coroutine:\n    at Function.Promise.coroutine (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:194:17)\n    at Function.create (F:\\WORK\\contacts\\backend\\services\\contact.js:13:24)\n    at F:\\WORK\\contacts\\backend\\controllers\\contact.js:27:48\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15\n    at create (F:\\WORK\\contacts\\backend\\controllers\\contact.js:30:11)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at PromiseSpawn._continue (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:159:21)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:99:10)\n    at Function.<anonymous> (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15)\n    at Function.create (F:\\WORK\\contacts\\backend\\services\\contact.js:17:12)\n    at F:\\WORK\\contacts\\backend\\controllers\\contact.js:27:48\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15\n    at create (F:\\WORK\\contacts\\backend\\controllers\\contact.js:30:11)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at F:\\WORK\\contacts\\backend\\server.js:19:5\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)","err_errors":"","err_message":"A value function wrappedPointCut() {\n        var Promise = PromiseProvider.get();\n\n        var _this = this;\n        var args = [].slice.call(arguments);\n        var lastArg = args.pop();\n        var fn;\n        var originalError = new Error();\n        var $results;\n        if (lastArg && typeof lastArg !== 'function') {\n          args.push(lastArg);\n        } else {\n          fn = lastArg;\n        }\n\n        var promise = new Promise.ES6(function(resolve, reject) {\n          args.push(function(error) {\n            if (error) {\n              // gh-2633: since VersionError is very generic, take the\n              // stack trace of the original save() function call rather\n              // than the async trace\n              if (error instanceof VersionError) {\n                error.stack = originalError.stack;\n              }\n              _this.$__handleReject(error);\n              reject(error);\n              return;\n            }\n\n            // There may be multiple results and promise libs other than\n            // mpromise don't support passing multiple values to `resolve()`\n            $results = Array.prototype.slice.call(arguments, 1);\n            resolve.apply(promise, $results);\n          });\n\n          _this[_newName].apply(_this, args);\n        });\n        if (fn) {\n          if (this.constructor.$wrapCallback) {\n            fn = this.constructor.$wrapCallback(fn);\n          }\n          return promise.then(\n            function() {\n              process.nextTick(function() {\n                fn.apply(null, [null].concat($results));\n              });\n            },\n            function(error) {\n              process.nextTick(function() {\n                fn(error);\n              });\n            });\n        }\n        return promise;\n      } was yielded that could not be treated as a promise\n\n    See http://goo.gl/MqrFmX\n\nFrom coroutine:\n    at Function.Promise.coroutine (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:194:17)\n    at Function.create (F:\\WORK\\contacts\\backend\\services\\contact.js:13:24)\n    at F:\\WORK\\contacts\\backend\\controllers\\contact.js:27:48\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15\n    at create (F:\\WORK\\contacts\\backend\\controllers\\contact.js:30:11)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)","message":"Something went wrong!"}
26-03-2017 18:31:59.1 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
26-03-2017 18:33:33.9 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 18:33:33.9 [ERROR] {"code":"E_UNEXPECTED","err_trace":"TypeError: A value function wrappedPointCut() {\n        var Promise = PromiseProvider.get();\n\n        var _this = this;\n        var args = [].slice.call(arguments);\n        var lastArg = args.pop();\n        var fn;\n        var originalError = new Error();\n        var $results;\n        if (lastArg && typeof lastArg !== 'function') {\n          args.push(lastArg);\n        } else {\n          fn = lastArg;\n        }\n\n        var promise = new Promise.ES6(function(resolve, reject) {\n          args.push(function(error) {\n            if (error) {\n              // gh-2633: since VersionError is very generic, take the\n              // stack trace of the original save() function call rather\n              // than the async trace\n              if (error instanceof VersionError) {\n                error.stack = originalError.stack;\n              }\n              _this.$__handleReject(error);\n              reject(error);\n              return;\n            }\n\n            // There may be multiple results and promise libs other than\n            // mpromise don't support passing multiple values to `resolve()`\n            $results = Array.prototype.slice.call(arguments, 1);\n            resolve.apply(promise, $results);\n          });\n\n          _this[_newName].apply(_this, args);\n        });\n        if (fn) {\n          if (this.constructor.$wrapCallback) {\n            fn = this.constructor.$wrapCallback(fn);\n          }\n          return promise.then(\n            function() {\n              process.nextTick(function() {\n                fn.apply(null, [null].concat($results));\n              });\n            },\n            function(error) {\n              process.nextTick(function() {\n                fn(error);\n              });\n            });\n        }\n        return promise;\n      } was yielded that could not be treated as a promise\n\n    See http://goo.gl/MqrFmX\n\nFrom coroutine:\n    at Function.Promise.coroutine (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:194:17)\n    at Function.create (F:\\WORK\\contacts\\backend\\services\\contact.js:13:24)\n    at F:\\WORK\\contacts\\backend\\controllers\\contact.js:27:48\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15\n    at create (F:\\WORK\\contacts\\backend\\controllers\\contact.js:30:11)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at PromiseSpawn._continue (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:159:21)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:99:10)\n    at Function.<anonymous> (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15)\n    at Function.create (F:\\WORK\\contacts\\backend\\services\\contact.js:17:12)\n    at F:\\WORK\\contacts\\backend\\controllers\\contact.js:27:48\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15\n    at create (F:\\WORK\\contacts\\backend\\controllers\\contact.js:30:11)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at F:\\WORK\\contacts\\backend\\server.js:19:5\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)","err_errors":"","err_message":"A value function wrappedPointCut() {\n        var Promise = PromiseProvider.get();\n\n        var _this = this;\n        var args = [].slice.call(arguments);\n        var lastArg = args.pop();\n        var fn;\n        var originalError = new Error();\n        var $results;\n        if (lastArg && typeof lastArg !== 'function') {\n          args.push(lastArg);\n        } else {\n          fn = lastArg;\n        }\n\n        var promise = new Promise.ES6(function(resolve, reject) {\n          args.push(function(error) {\n            if (error) {\n              // gh-2633: since VersionError is very generic, take the\n              // stack trace of the original save() function call rather\n              // than the async trace\n              if (error instanceof VersionError) {\n                error.stack = originalError.stack;\n              }\n              _this.$__handleReject(error);\n              reject(error);\n              return;\n            }\n\n            // There may be multiple results and promise libs other than\n            // mpromise don't support passing multiple values to `resolve()`\n            $results = Array.prototype.slice.call(arguments, 1);\n            resolve.apply(promise, $results);\n          });\n\n          _this[_newName].apply(_this, args);\n        });\n        if (fn) {\n          if (this.constructor.$wrapCallback) {\n            fn = this.constructor.$wrapCallback(fn);\n          }\n          return promise.then(\n            function() {\n              process.nextTick(function() {\n                fn.apply(null, [null].concat($results));\n              });\n            },\n            function(error) {\n              process.nextTick(function() {\n                fn(error);\n              });\n            });\n        }\n        return promise;\n      } was yielded that could not be treated as a promise\n\n    See http://goo.gl/MqrFmX\n\nFrom coroutine:\n    at Function.Promise.coroutine (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:194:17)\n    at Function.create (F:\\WORK\\contacts\\backend\\services\\contact.js:13:24)\n    at F:\\WORK\\contacts\\backend\\controllers\\contact.js:27:48\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15\n    at create (F:\\WORK\\contacts\\backend\\controllers\\contact.js:30:11)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)","message":"Something went wrong!"}
26-03-2017 18:33:33.9 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
26-03-2017 18:34:30.8 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 18:34:30.8 [ERROR] {"code":"E_UNEXPECTED","err_trace":"TypeError: A value undefined was yielded that could not be treated as a promise\n\n    See http://goo.gl/MqrFmX\n\nFrom coroutine:\n    at Function.Promise.coroutine (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:194:17)\n    at Function.create (F:\\WORK\\contacts\\backend\\services\\contact.js:13:24)\n    at F:\\WORK\\contacts\\backend\\controllers\\contact.js:27:48\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15\n    at create (F:\\WORK\\contacts\\backend\\controllers\\contact.js:30:11)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at PromiseSpawn._continue (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:159:21)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:99:10)\n    at Function.<anonymous> (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15)\n    at Function.create (F:\\WORK\\contacts\\backend\\services\\contact.js:19:12)\n    at F:\\WORK\\contacts\\backend\\controllers\\contact.js:27:48\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15\n    at create (F:\\WORK\\contacts\\backend\\controllers\\contact.js:30:11)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at F:\\WORK\\contacts\\backend\\server.js:19:5\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)","err_errors":"","err_message":"A value undefined was yielded that could not be treated as a promise\n\n    See http://goo.gl/MqrFmX\n\nFrom coroutine:\n    at Function.Promise.coroutine (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:194:17)\n    at Function.create (F:\\WORK\\contacts\\backend\\services\\contact.js:13:24)\n    at F:\\WORK\\contacts\\backend\\controllers\\contact.js:27:48\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15\n    at create (F:\\WORK\\contacts\\backend\\controllers\\contact.js:30:11)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)","message":"Something went wrong!"}
26-03-2017 18:34:30.8 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
26-03-2017 18:36:14.7 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 18:36:14.7 [ERROR] {"code":"E_UNEXPECTED","err_trace":"TypeError: A value undefined was yielded that could not be treated as a promise\n\n    See http://goo.gl/MqrFmX\n\nFrom coroutine:\n    at Function.Promise.coroutine (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:194:17)\n    at Function.create (F:\\WORK\\contacts\\backend\\services\\contact.js:13:24)\n    at F:\\WORK\\contacts\\backend\\controllers\\contact.js:27:48\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15\n    at create (F:\\WORK\\contacts\\backend\\controllers\\contact.js:30:11)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at PromiseSpawn._continue (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:159:21)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:99:10)\n    at Function.<anonymous> (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15)\n    at Function.create (F:\\WORK\\contacts\\backend\\services\\contact.js:19:12)\n    at F:\\WORK\\contacts\\backend\\controllers\\contact.js:27:48\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15\n    at create (F:\\WORK\\contacts\\backend\\controllers\\contact.js:30:11)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at F:\\WORK\\contacts\\backend\\server.js:19:5\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)","err_errors":"","err_message":"A value undefined was yielded that could not be treated as a promise\n\n    See http://goo.gl/MqrFmX\n\nFrom coroutine:\n    at Function.Promise.coroutine (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:194:17)\n    at Function.create (F:\\WORK\\contacts\\backend\\services\\contact.js:13:24)\n    at F:\\WORK\\contacts\\backend\\controllers\\contact.js:27:48\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15\n    at create (F:\\WORK\\contacts\\backend\\controllers\\contact.js:30:11)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)","message":"Something went wrong!"}
26-03-2017 18:36:14.7 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
26-03-2017 18:36:27.8 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 18:36:27.8 [ERROR] {"code":"E_UNEXPECTED","err_trace":"TypeError: contact.save is not a function\n    at Function.<anonymous> (F:\\WORK\\contacts\\backend\\services\\contact.js:18:37)\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at Function.<anonymous> (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15)\n    at Function.create (F:\\WORK\\contacts\\backend\\services\\contact.js:20:12)\n    at F:\\WORK\\contacts\\backend\\controllers\\contact.js:27:48\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15\n    at create (F:\\WORK\\contacts\\backend\\controllers\\contact.js:30:11)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at F:\\WORK\\contacts\\backend\\server.js:19:5\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:317:13)","err_errors":"","err_message":"contact.save is not a function","message":"Something went wrong!"}
26-03-2017 18:36:27.8 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
26-03-2017 18:39:46.4 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 18:39:46.4 [ERROR] {"code":"E_UNEXPECTED","err_trace":"TypeError: contact.save is not a function\n    at Function.<anonymous> (F:\\WORK\\contacts\\backend\\services\\contact.js:18:37)\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at Function.<anonymous> (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15)\n    at Function.create (F:\\WORK\\contacts\\backend\\services\\contact.js:20:12)\n    at F:\\WORK\\contacts\\backend\\controllers\\contact.js:27:48\n    at next (native)\n    at tryCatcher (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:97:49)\n    at F:\\WORK\\contacts\\backend\\node_modules\\bluebird\\js\\release\\generators.js:201:15\n    at create (F:\\WORK\\contacts\\backend\\controllers\\contact.js:30:11)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at F:\\WORK\\contacts\\backend\\server.js:19:5\n    at Layer.handle [as handle_request] (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (F:\\WORK\\contacts\\backend\\node_modules\\express\\lib\\router\\index.js:317:13)","err_errors":"","err_message":"contact.save is not a function","message":"Something went wrong!"}
26-03-2017 18:39:46.4 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
26-03-2017 18:45:31.5 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 18:45:31.5 [ERROR] {"code":"E_UNEXPECTED","err_trace":"ValidationError: Contact validation failed\n    at MongooseError.ValidationError (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\error\\validation.js:23:11)\n    at model.Document.invalidate (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\document.js:1535:32)\n    at EmbeddedDocument.invalidate (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\types\\embedded.js:223:19)\n    at F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\document.js:1410:17\n    at validate (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\schematype.js:707:7)\n    at F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\schematype.js:752:11\n    at Array.forEach (native)\n    at SchemaString.SchemaType.doValidate (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\schematype.js:712:19)\n    at F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\document.js:1408:9\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)","err_errors":{"emails.0.type":{"message":"`work` is not a valid enum value for path `type`.","name":"ValidatorError","properties":{"enumValues":["WORK","PERSONAL"],"type":"enum","message":"`{VALUE}` is not a valid enum value for path `{PATH}`.","path":"type","value":"work"},"kind":"enum","path":"type","value":"work"},"emails.1.type":{"message":"`personal` is not a valid enum value for path `type`.","name":"ValidatorError","properties":{"enumValues":["WORK","PERSONAL"],"type":"enum","message":"`{VALUE}` is not a valid enum value for path `{PATH}`.","path":"type","value":"personal"},"kind":"enum","path":"type","value":"personal"},"phones.0.type":{"message":"`work` is not a valid enum value for path `type`.","name":"ValidatorError","properties":{"enumValues":["WORK","PERSONAL"],"type":"enum","message":"`{VALUE}` is not a valid enum value for path `{PATH}`.","path":"type","value":"work"},"kind":"enum","path":"type","value":"work"},"phones.1.type":{"message":"`work` is not a valid enum value for path `type`.","name":"ValidatorError","properties":{"enumValues":["WORK","PERSONAL"],"type":"enum","message":"`{VALUE}` is not a valid enum value for path `{PATH}`.","path":"type","value":"work"},"kind":"enum","path":"type","value":"work"},"emails.1.email":{"message":"Validator failed for path `email` with value `devesh.jadon@venturepact.com`","name":"ValidatorError","properties":{"type":"user defined","message":"Validator failed for path `{PATH}` with value `{VALUE}`","path":"email","value":"devesh.jadon@venturepact.com"},"kind":"user defined","path":"email","value":"devesh.jadon@venturepact.com"},"emails.0.email":{"message":"Validator failed for path `email` with value `jadon@sfdfd.vom`","name":"ValidatorError","properties":{"type":"user defined","message":"Validator failed for path `{PATH}` with value `{VALUE}`","path":"email","value":"jadon@sfdfd.vom"},"kind":"user defined","path":"email","value":"jadon@sfdfd.vom"}},"err_message":"Contact validation failed","message":"Something went wrong!"}
26-03-2017 18:45:31.5 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
26-03-2017 18:46:15.5 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 18:46:15.5 [ERROR] {"code":"E_UNEXPECTED","err_trace":"ValidationError: Contact validation failed\n    at MongooseError.ValidationError (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\error\\validation.js:23:11)\n    at model.Document.invalidate (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\document.js:1535:32)\n    at EmbeddedDocument.invalidate (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\types\\embedded.js:223:19)\n    at F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\document.js:1410:17\n    at validate (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\schematype.js:707:7)\n    at F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\schematype.js:752:11\n    at Array.forEach (native)\n    at SchemaString.SchemaType.doValidate (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\schematype.js:712:19)\n    at F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\document.js:1408:9\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)","err_errors":{"emails.0.type":{"message":"`work` is not a valid enum value for path `type`.","name":"ValidatorError","properties":{"enumValues":["WORK","PERSONAL"],"type":"enum","message":"`{VALUE}` is not a valid enum value for path `{PATH}`.","path":"type","value":"work"},"kind":"enum","path":"type","value":"work"},"emails.1.type":{"message":"`personal` is not a valid enum value for path `type`.","name":"ValidatorError","properties":{"enumValues":["WORK","PERSONAL"],"type":"enum","message":"`{VALUE}` is not a valid enum value for path `{PATH}`.","path":"type","value":"personal"},"kind":"enum","path":"type","value":"personal"},"phones.0.type":{"message":"`work` is not a valid enum value for path `type`.","name":"ValidatorError","properties":{"enumValues":["WORK","PERSONAL"],"type":"enum","message":"`{VALUE}` is not a valid enum value for path `{PATH}`.","path":"type","value":"work"},"kind":"enum","path":"type","value":"work"},"phones.1.type":{"message":"`work` is not a valid enum value for path `type`.","name":"ValidatorError","properties":{"enumValues":["WORK","PERSONAL"],"type":"enum","message":"`{VALUE}` is not a valid enum value for path `{PATH}`.","path":"type","value":"work"},"kind":"enum","path":"type","value":"work"}},"err_message":"Contact validation failed","message":"Something went wrong!"}
26-03-2017 18:46:15.5 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
26-03-2017 18:46:39.3 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 18:46:39.3 [ERROR] {"code":"E_UNEXPECTED","err_trace":"ValidationError: Contact validation failed\n    at MongooseError.ValidationError (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\error\\validation.js:23:11)\n    at model.Document.invalidate (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\document.js:1535:32)\n    at EmbeddedDocument.invalidate (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\types\\embedded.js:223:19)\n    at F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\document.js:1410:17\n    at validate (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\schematype.js:707:7)\n    at F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\schematype.js:752:11\n    at Array.forEach (native)\n    at SchemaString.SchemaType.doValidate (F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\schematype.js:712:19)\n    at F:\\WORK\\contacts\\backend\\node_modules\\mongoose\\lib\\document.js:1408:9\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)","err_errors":{"emails.0.type":{"message":"`work` is not a valid enum value for path `type`.","name":"ValidatorError","properties":{"enumValues":["WORK","PERSONAL"],"type":"enum","message":"`{VALUE}` is not a valid enum value for path `{PATH}`.","path":"type","value":"work"},"kind":"enum","path":"type","value":"work"},"emails.1.type":{"message":"`personal` is not a valid enum value for path `type`.","name":"ValidatorError","properties":{"enumValues":["WORK","PERSONAL"],"type":"enum","message":"`{VALUE}` is not a valid enum value for path `{PATH}`.","path":"type","value":"personal"},"kind":"enum","path":"type","value":"personal"},"phones.0.type":{"message":"`work` is not a valid enum value for path `type`.","name":"ValidatorError","properties":{"enumValues":["WORK","PERSONAL"],"type":"enum","message":"`{VALUE}` is not a valid enum value for path `{PATH}`.","path":"type","value":"work"},"kind":"enum","path":"type","value":"work"},"phones.1.type":{"message":"`work` is not a valid enum value for path `type`.","name":"ValidatorError","properties":{"enumValues":["WORK","PERSONAL"],"type":"enum","message":"`{VALUE}` is not a valid enum value for path `{PATH}`.","path":"type","value":"work"},"kind":"enum","path":"type","value":"work"}},"err_message":"Contact validation failed","message":"Something went wrong!"}
26-03-2017 18:46:39.3 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
26-03-2017 20:07:56.0 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 20:07:56.0 [ERROR] {"code":11000,"err_trace":"MongoError: E11000 duplicate key error collection: contacts.contacts index: emails.email_1 dup key: { : null }\n    at Function.MongoError.create (F:\\WORK\\contact-backend\\node_modules\\mongodb-core\\lib\\error.js:31:11)\n    at toError (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:139:22)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\collection.js:659:23\n    at handleCallback (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:120:56)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\bulk\\unordered.js:465:9\n    at handleCallback (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:120:56)\n    at resultHandler (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\bulk\\unordered.js:413:5)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb-core\\lib\\connection\\pool.js:461:18\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)","err_errors":"","err_message":"E11000 duplicate key error collection: contacts.contacts index: emails.email_1 dup key: { : null }","message":"Something went wrong!"}
26-03-2017 20:07:56.0 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
26-03-2017 20:09:46.5 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 20:09:46.5 [ERROR] {"code":11000,"err_trace":"MongoError: E11000 duplicate key error collection: contacts.contacts index: emails.email_1 dup key: { : null }\n    at Function.MongoError.create (F:\\WORK\\contact-backend\\node_modules\\mongodb-core\\lib\\error.js:31:11)\n    at toError (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:139:22)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\collection.js:659:23\n    at handleCallback (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:120:56)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\bulk\\unordered.js:465:9\n    at handleCallback (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:120:56)\n    at resultHandler (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\bulk\\unordered.js:413:5)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb-core\\lib\\connection\\pool.js:461:18\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)","err_errors":"","err_message":"E11000 duplicate key error collection: contacts.contacts index: emails.email_1 dup key: { : null }","message":"Something went wrong!"}
26-03-2017 20:09:46.5 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
26-03-2017 20:11:43.5 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 20:11:43.5 [ERROR] {"code":11000,"err_trace":"MongoError: E11000 duplicate key error collection: contacts.contacts index: emails.email_1 dup key: { : null }\n    at Function.MongoError.create (F:\\WORK\\contact-backend\\node_modules\\mongodb-core\\lib\\error.js:31:11)\n    at toError (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:139:22)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\collection.js:659:23\n    at handleCallback (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:120:56)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\bulk\\unordered.js:465:9\n    at handleCallback (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:120:56)\n    at resultHandler (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\bulk\\unordered.js:413:5)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb-core\\lib\\connection\\pool.js:461:18\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)","err_errors":"","err_message":"E11000 duplicate key error collection: contacts.contacts index: emails.email_1 dup key: { : null }","message":"Something went wrong!"}
26-03-2017 20:11:43.5 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
26-03-2017 20:13:12.6 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 20:13:12.7 [ERROR] {"code":11000,"err_trace":"MongoError: E11000 duplicate key error collection: contacts.contacts index: emails.email_1 dup key: { : null }\n    at Function.MongoError.create (F:\\WORK\\contact-backend\\node_modules\\mongodb-core\\lib\\error.js:31:11)\n    at toError (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:139:22)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\collection.js:659:23\n    at handleCallback (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:120:56)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\bulk\\unordered.js:465:9\n    at handleCallback (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:120:56)\n    at resultHandler (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\bulk\\unordered.js:413:5)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb-core\\lib\\connection\\pool.js:461:18\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)","err_errors":"","err_message":"E11000 duplicate key error collection: contacts.contacts index: emails.email_1 dup key: { : null }","message":"Something went wrong!"}
26-03-2017 20:13:12.7 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
26-03-2017 20:13:48.9 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 20:13:48.9 [ERROR] {"code":11000,"err_trace":"MongoError: E11000 duplicate key error collection: contacts.contacts index: emails.email_1 dup key: { : null }\n    at Function.MongoError.create (F:\\WORK\\contact-backend\\node_modules\\mongodb-core\\lib\\error.js:31:11)\n    at toError (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:139:22)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\collection.js:659:23\n    at handleCallback (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:120:56)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\bulk\\unordered.js:465:9\n    at handleCallback (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:120:56)\n    at resultHandler (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\bulk\\unordered.js:413:5)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb-core\\lib\\connection\\pool.js:461:18\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)","err_errors":"","err_message":"E11000 duplicate key error collection: contacts.contacts index: emails.email_1 dup key: { : null }","message":"Something went wrong!"}
26-03-2017 20:13:48.9 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
26-03-2017 20:15:49.2 [ERROR] -----------------------"Error" spotted---------------------------------
26-03-2017 20:15:49.2 [ERROR] {"code":11000,"err_trace":"MongoError: E11000 duplicate key error collection: contacts.contacts index: phones.phone_1 dup key: { : \"09780080358\" }\n    at Function.MongoError.create (F:\\WORK\\contact-backend\\node_modules\\mongodb-core\\lib\\error.js:31:11)\n    at toError (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:139:22)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\collection.js:659:23\n    at handleCallback (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:120:56)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\bulk\\unordered.js:465:9\n    at handleCallback (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\utils.js:120:56)\n    at resultHandler (F:\\WORK\\contact-backend\\node_modules\\mongodb\\lib\\bulk\\unordered.js:413:5)\n    at F:\\WORK\\contact-backend\\node_modules\\mongodb-core\\lib\\connection\\pool.js:461:18\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)","err_errors":"","err_message":"E11000 duplicate key error collection: contacts.contacts index: phones.phone_1 dup key: { : \"09780080358\" }","message":"Something went wrong!"}
26-03-2017 20:15:49.2 [ERROR] -------XXXXXX----------"Error" spotted---------------XXXXXX------------
